### ISSUE TITLE
Error in AAI calculation

### ISSUE THREAD

**Issue by ctSkennerton** [dparks1134/CompareM#1]
Hey Donovan,

I'm running through the aai workflow that you've got and I'm running into the following error, any ideas what might cause this.

```
$ comparem aai rblast/ .

*******************************************************************************
 [CompareM - aai] Calculating the AAI between homologs in genome pairs.
*******************************************************************************

  Calculating length of genes in each genome.

  Indexing blast hits.

  Calculating amino acid identity between all pairs of genomes:
Process Process-1:1:ing 2 of 378 (0.53%) genomes.
Traceback (most recent call last):
  File "/opt/qiime/1.8.0/python-2.7.3-release/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/opt/qiime/1.8.0/python-2.7.3-release/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cts/local/lib/python2.7/site-packages/biolib/parallel.py", line 106, in __producer
    rtn = producer_callback(dataItem)
  File "/home/cts/local/lib/python2.7/site-packages/comparem/aai_calculator.py", line 190, in _producer
    genome_idB, genome_idA)
  File "/home/cts/local/lib/python2.7/site-packages/comparem/aai_calculator.py", line 131, in _valid_hits
    start_pos, end_pos = offset_table[query_genome_id]
KeyError: 'Methylohalobius_crimeensis_10Ki_genes'
```

**Comment by dparks1134** [comment]
Hey Connor,

I've pushed the latest changed to CompareM and biolib (dependency of CompareM) to git and pypi. Can you sync to the latest code and see if the problem persists. What is the full name for the file 'Methylohalobius_crimeensis_10Ki_genes'? Does it just end with a '.faa.'?

Cheers,
Donovan

**Comment by ctSkennerton** [comment]
Still get the error, and the corresponding file does just end in '.faa'. I actually get this with a lot of the genomes not just this one. Here is the contents of the 'genes' subdirectory:

```
call_genes.summary.tsv                       Methylocaldum_szegediense_genes.faa            Methylomicrobium_agile_genes.fna         Methylomonas_sp._FJG1.gff
Methylobacter_luteus_genes.faa               Methylocaldum_szegediense_genes.fna            Methylomicrobium_agile.gff               Methylomonas_sp._LW13_genes.faa
Methylobacter_luteus_genes.fna               Methylocaldum_szegediense.gff                  Methylomicrobium_album_genes.faa         Methylomonas_sp._LW13_genes.fna
Methylobacter_luteus.gff                     Methylococcaceae_bacterium_73a_genes.faa       Methylomicrobium_album_genes.fna         Methylomonas_sp._LW13.gff
Methylobacter_marinus_genes.faa              Methylococcaceae_bacterium_73a_genes.fna       Methylomicrobium_album.gff               Methylomonas_sp._MK1_genes.faa
Methylobacter_marinus_genes.fna              Methylococcaceae_bacterium_73a.gff             Methylomicrobium_alcaliphilum_genes.faa  Methylomonas_sp._MK1_genes.fna
Methylobacter_marinus.gff                    Methylococcus_capsulatus_ATCC_19069_genes.faa  Methylomicrobium_alcaliphilum_genes.fna  Methylomonas_sp._MK1.gff
Methylobacter_sp._BBA5.1_genes.faa           Methylococcus_capsulatus_ATCC_19069_genes.fna  Methylomicrobium_alcaliphilum.gff        Methylosarcina_fibrata_genes.faa
Methylobacter_sp._BBA5.1_genes.fna           Methylococcus_capsulatus_ATCC_19069.gff        Methylomicrobium_buryatense_genes.faa    Methylosarcina_fibrata_genes.fna
Methylobacter_sp._BBA5.1.gff                 Methylococcus_capsulatus_Bath_genes.faa        Methylomicrobium_buryatense_genes.fna    Methylosarcina_fibrata.gff
Methylobacter_tundripaludum_31_32_genes.faa  Methylococcus_capsulatus_Bath_genes.fna        Methylomicrobium_buryatense.gff          Methylosarcina_lacus_genes.faa
Methylobacter_tundripaludum_31_32_genes.fna  Methylococcus_capsulatus_Bath.gff              Methylomicrobium_kenyense_genes.faa      Methylosarcina_lacus_genes.fna
Methylobacter_tundripaludum_31_32.gff        Methyloglobulus_morosus_genes.faa              Methylomicrobium_kenyense_genes.fna      Methylosarcina_lacus.gff
Methylobacter_tundripaludum_SV96_genes.faa   Methyloglobulus_morosus_genes.fna              Methylomicrobium_kenyense.gff            Methylothermus_fortula_2044CB42_genes.faa
Methylobacter_tundripaludum_SV96_genes.fna   Methyloglobulus_morosus.gff                    Methylomonas_methanica_genes.faa         Methylothermus_fortula_2044CB42_genes.fna
Methylobacter_tundripaludum_SV96.gff         Methylohalobius_crimeensis_10Ki_genes.faa      Methylomonas_methanica_genes.fna         Methylothermus_fortula_2044CB42.gff
Methylobacter_whittenburyi_genes.faa         Methylohalobius_crimeensis_10Ki_genes.fna      Methylomonas_methanica.gff               Methylovulum_miyakonense_genes.faa
Methylobacter_whittenburyi_genes.fna         Methylohalobius_crimeensis_10Ki.gff            Methylomonas_sp._11b_genes.faa           Methylovulum_miyakonense_genes.fna
Methylobacter_whittenburyi.gff               Methylomarinum_vadi_genes.faa                  Methylomonas_sp._11b_genes.fna           Methylovulum_miyakonense.gff
Methylocaldum_sp._175_genes.faa              Methylomarinum_vadi_genes.fna                  Methylomonas_sp._11b.gff
Methylocaldum_sp._175_genes.fna              Methylomarinum_vadi.gff                        Methylomonas_sp._FJG1_genes.faa
Methylocaldum_sp._175.gff                    Methylomicrobium_agile_genes.faa               Methylomonas_sp._FJG1_genes.fna
```

**Comment by dparks1134** [comment]
Hey Connor,

The error isn't obvious to me, but it is likely due to some bad filename management on my part. Obviously you must of run <code>comparem rblast</code> first. Did you run these on previously called genes or did you use <code>comparem call_genes</code> on nucleotide sequences? Either way, if you send me your starting files and a quick description of what you did, I'll try to reproduce the issue on my end.

Cheers,
Donovan

**Comment by dparks1134** [comment]
This issue was related to the version of DIAMOND being used. CompareM requires DIAMOND >= 0.7.9.
