### ISSUE TITLE
ERROR:Input file does not exists

### ISSUE THREAD

**Issue by FlamySYSU** [dparks1134/CompareM#19]
Hi
I got an error when runing comparem aai_wf, even aa_usage and some other function, Im afraid only comparem -h can show normal results, here is the error message:

$/data/manik/software/anaconda3/envs/python2.7/bin/comparem aai_wf Tumba6 aai_output
[2018-10-25 20:21:36] INFO: CompareM v0.0.23
[2018-10-25 20:21:36] INFO: comparem aai_wf Tumba6 aai_output
[2018-10-25 20:21:36] INFO: Identifying genes within genomes: 
[2018-10-25 20:21:36] ERROR: Input file does not exists: /tmp/tmply4eMZ/4/Anaerolinea thermolimosa strain=IMO-1.gff

Unexpected error: <type 'exceptions.AttributeError'>
Traceback (most recent call last):
  File "/data/manik/software/anaconda3/envs/python2.7/bin/comparem", line 375, in <module>
    parser.parse_options(args)
  File "/data/manik/software/anaconda3/envs/python2.7/lib/python2.7/site-packages/comparem/main.py", line 442, in parse_options
    self.call_genes(options)
  File "/data/manik/software/anaconda3/envs/python2.7/lib/python2.7/site-packages/comparem/main.py", line 157, in call_genes
    for genome_id, stats in summary_stats.iteritems():
AttributeError: 'NoneType' object has no attribute 'iteritems'

Pls sombody help me,:( however,thanks in advance for any help

FlamySYSU

**Comment by dparks1134** [comment]
Closing old issues as CompareM is being migrated to Python 3.
