### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'iteritems'

### ISSUE THREAD

**Issue by Felixseetoo** [dparks1134/CompareM#23]
Hi,

I got error as below while trying to run the aai_wf command. May I know how to solve this issue ?

$ comparem aai_wf Fasta_OAT Fasta_OAT/aai_output --file_ext .fasta
[2019-01-11 15:57:19] INFO: CompareM v0.0.23
[2019-01-11 15:57:19] INFO: comparem aai_wf Fasta_OAT Fasta_OAT/aai_output --file_ext .fasta
[2019-01-11 15:57:19] INFO: Identifying genes within genomes: 
Process Process-1:1:g 0 of 104 (0.00%) genomes.
Traceback (most recent call last):
  File "/home/umhir10/miniconda2/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/home/umhir10/miniconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/umhir10/miniconda2/lib/python2.7/site-packages/biolib/parallel.py", line 107, in __producer
    rtn = producer_callback(dataItem)
  File "/home/umhir10/miniconda2/lib/python2.7/site-packages/biolib/external/prodigal.py", line 122, in _producer
    prodigalParser = ProdigalGeneFeatureParser(gff_file_tmp)
  File "/home/umhir10/miniconda2/lib/python2.7/site-packages/biolib/external/prodigal.py", line 285, in __init__
    self.__parseGFF(filename)
  File "/home/umhir10/miniconda2/lib/python2.7/site-packages/biolib/external/prodigal.py", line 302, in __parseGFF
    self.translationTable = line.split(';')[4]
IndexError: list index out of range

Unexpected error: <type 'exceptions.AttributeError'>
Traceback (most recent call last):
  File "/home/umhir10/miniconda2/bin/comparem", line 375, in <module>
    parser.parse_options(args)
  File "/home/umhir10/miniconda2/lib/python2.7/site-packages/comparem/main.py", line 442, in parse_options
    self.call_genes(options)
  File "/home/umhir10/miniconda2/lib/python2.7/site-packages/comparem/main.py", line 157, in call_genes
    for genome_id, stats in summary_stats.iteritems():
AttributeError: 'NoneType' object has no attribute 'iteritems'

Thanks.

**Comment by vinisalazar** [comment]
Seems like a problem when running the Prodigal package. Do you by any chance have any input filenames with special characters such as "(" or "|"? This can make it confusing for Prodigal to run.

**Comment by Felixseetoo** [comment]
Hi, there is no special character in the filenames. But there are some "\" in the header of the fasta file, will it be affected?

**Comment by flyant2** [comment]
For
File "/home/umhir10/miniconda2/lib/python2.7/site-packages/comparem/main.py", line 157, in ...
AttributeError: 'NoneType' object has no attribute 'iteritems'

Just change '**iteritems**' to '**items**' in File "/home/umhir10/miniconda2/lib/python2.7/site-packages/comparem/main.py".

good luck!
