### ISSUE TITLE
AttributeError: 'Diamond' object has no attribute 'make_database'

### ISSUE THREAD

**Issue by fujch7** [dparks1134/CompareM#27]
[2020-03-02 01:52:50] INFO: CompareM v0.0.23
[2020-03-02 01:52:50] INFO: comparem aai_wf /home/data/AAI/input/0227/ /home/data/AAI/output/ --cpu 2
[2020-03-02 01:52:50] INFO: Identifying genes within genomes: 
  Finished processing 45 of 45 (100.00%) genomes.
[2020-03-02 02:04:30] INFO: Identified genes written to: /home/data/AAI/output/genes
[2020-03-02 02:04:30] INFO: Appending genome identifiers to query genes.
[2020-03-02 02:04:32] INFO: Creating DIAMOND database (be patient!).

Unexpected error: <type 'exceptions.AttributeError'>
Traceback (most recent call last):
  File "/usr/bin/comparem", line 375, in <module>
    parser.parse_options(args)
  File "/usr/lib/python2.7/site-packages/comparem/main.py", line 448, in parse_options
    self.similarity(options)
  File "/usr/lib/python2.7/site-packages/comparem/main.py", line 185, in similarity
    options.output_dir)
  File "/usr/lib/python2.7/site-packages/comparem/similarity_search.py", line 442, in run
    output_dir)
  File "/usr/lib/python2.7/site-packages/comparem/similarity_search.py", line 179, in _run_self_diamond
    diamond.make_database(query_gene_file, diamond_db)
AttributeError: 'Diamond' object has no attribute 'make_database'

# how could I solve  this  problem? It would  be appreciated that someone can help me.

**Comment by ptittomate** [comment]
Hi, I have the same problem as you & I have resolved it as follows:
To search the library path of DIAMOND in Python
      python -c "import biolib.external.diamond; print(biolib.external.diamond.__file__)"
      --> for me : /usr/local/lib/python2.7/dist-packages/biolib/external/diamond.pyc
EDIT the file /usr/local/lib/python2.7/dist-packages/biolib/external/diamond.py
in line 67 :  def create_db(self, prot_file, db_file):
       -->   change "create_db"    to    make_database"
and in line 77 :  os.system(self.create_blastp_db_cmd(prot_file, db_file))
       -->   change "create_blastp_db_cmd"  to "create_db_cmd"
IT WORK FOR ME :) good luck

**Comment by fujch7** [comment]
thanks very much！！It worked！！！！

**Comment by fujch7** [comment]
> 
> 
> Hi, I have the same problem as you & I have resolved it as follows:
> To search the library path of DIAMOND in Python
> python -c "import biolib.external.diamond; print(biolib.external.diamond._ _file_ _)"
> --> for me : /usr/local/lib/python2.7/dist-packages/biolib/external/diamond.pyc
> EDIT the file /usr/local/lib/python2.7/dist-packages/biolib/external/diamond.py
> in line 67 : def create_db(self, prot_file, db_file):
> --> change "create_db" to make_database"
> and in line 77 : os.system(self.create_blastp_db_cmd(prot_file, db_file))
> --> change "create_blastp_db_cmd" to "create_db_cmd"
> IT WORK FOR ME :) good luck
thanks very much！！It worked！！！！

**Comment by fujch7** [comment]
I have another question. Is there any command to output an AAI MATRIX?

**Comment by dparks1134** [comment]
Hi,

You can do this with the `diss` command by providing the aai_summary.tsv as
input along with appropriate header column names:
> compare diss -h

Cheers,
Donovan

**Comment by dparks1134** [comment]
I have just updated CompareM to v0.1.0. This addresses your previous issue and moves CompareM from Python 2 to Python 3.
