### ISSUE TITLE
TypeError: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by dikshyantg** [dparks1134/CompareM#31]
Hi,
I was trying to perform comparM aai_wf on two genomes of bacteria . I used the command 
aai_wf mygenomes out --proteins 
The error  I received was -

[2020-05-16 10:35:23] INFO: CompareM v0.1.1
[2020-05-16 10:35:23] INFO: comparem aai_wf mygenomes out --proteins
[2020-05-16 10:35:23] WARNING: Changing file extension from 'fna' to 'faa' since 'proteins' flag was given.
[2020-05-16 10:35:23] INFO: Appending genome identifiers to query genes.
[2020-05-16 10:35:23] INFO: Creating DIAMOND database (be patient!).
[2020-05-16 10:35:23] INFO: Performing self similarity sequence between genomes (be patient!).
[2020-05-16 10:35:30] INFO: Sorting table with hits (be patient!).
[2020-05-16 10:35:30] INFO: Sequence similarity results written to: out/similarity
[2020-05-16 10:35:30] INFO: Calculating length of genes.
[2020-05-16 10:35:30] INFO: Indexing sorted hit table.
[2020-05-16 10:35:30] INFO: Calculating AAI between all 0 pairs of genomes:
[2020-05-16 10:35:30] WARNING: No genome pairs identified.

Unexpected error: <class 'TypeError'>
Traceback (most recent call last):
  File "/home/dikshyant/anaconda3/bin/comparem", line 377, in <module>
    parser.parse_options(args)
  File "/home/dikshyant/anaconda3/lib/python3.7/site-packages/comparem/main.py", line 465, in parse_options
    self.aai(options)
  File "/home/dikshyant/anaconda3/lib/python3.7/site-packages/comparem/main.py", line 202, in aai
    options.output_dir)
TypeError: cannot unpack non-iterable NoneType object

How do I solve it?

**Comment by dparks1134** [comment]
Perhaps this is an issue with the sort command. What flavour of Linux are you using? See the note at the top of the CompareM README file:
https://github.com/dparks1134/CompareM
