### ISSUE TITLE
self.logger.error(f'Unrecognized image format: {img_format}')

### ISSUE THREAD

**Issue by gamlopez** [dparks1134/CompareM#35]
Dear authors:
I have installed compareM in debian 8 and 9 operating system, python 2.7 via pip install which installs all the dependencies (I already verified that they are correctly installed), I installed the diamond and prodigal dependencies. At this point everything looks ok, but when I try to run it with parameters and without parameters throws the following error:

(base) jmanuel@galileo:~$ comparem
Traceback (most recent call last):
  File "/usr/local/bin/comparem", line 37, in <module>
    from comparem.main import OptionsParser
  File "/usr/local/lib/python2.7/dist-packages/comparem/main.py", line 33, in <module>
    from comparem.plots.heatmap import Heatmap
  File "/usr/local/lib/python2.7/dist-packages/comparem/plots/heatmap.py", line 33, in <module>
    from biolib.plots.abstract_plot import AbstractPlot
  File "/usr/local/lib/python2.7/dist-packages/biolib/plots/abstract_plot.py", line 95
    self.logger.error(f'Unrecognized image format: {img_format}')
                                                               
SyntaxError: invalid syntax
(base) jmanuel@galileo:~$ comparem -h
Traceback (most recent call last):
  File "/usr/local/bin/comparem", line 37, in <module>
    from comparem.main import OptionsParser
  File "/usr/local/lib/python2.7/dist-packages/comparem/main.py", line 33, in <module>
    from comparem.plots.heatmap import Heatmap
  File "/usr/local/lib/python2.7/dist-packages/comparem/plots/heatmap.py", line 33, in <module>
    from biolib.plots.abstract_plot import AbstractPlot
  File "/usr/local/lib/python2.7/dist-packages/biolib/plots/abstract_plot.py", line 95
    self.logger.error(f'Unrecognized image format: {img_format}')
                                                               
SyntaxError: invalid syntax

Thank you for your time

Best regards,

**Comment by dparks1134** [comment]
Hi. The latest version of CompareM requires Python 3.x. I suspect this will resolve the reported issue.

**Comment by gamlopez** [comment]
> Hi. The latest version of CompareM requires Python 3.x. I suspect this will resolve the reported issue.

Thank you for your replay.
I used python 3.X for this time but i have the same issue.


galileo:/home/jmanuel# pip3 install comparem
Requirement already satisfied: comparem in /usr/local/lib/python3.5/dist-packages
Requirement already satisfied: matplotlib>=1.3.1 in /usr/local/lib/python3.5/dist-packages (from comparem)
Requirement already satisfied: biolib>=0.1.0 in /usr/local/lib/python3.5/dist-packages (from comparem)
Requirement already satisfied: numpy>=1.8.0 in /usr/local/lib/python3.5/dist-packages (from comparem)
Requirement already satisfied: scipy>=0.9.0 in /usr/local/lib/python3.5/dist-packages (from comparem)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.5/dist-packages (from matplotlib>=1.3.1->comparem)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.5/dist-packages (from matplotlib>=1.3.1->comparem)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.5/dist-packages (from matplotlib>=1.3.1->comparem)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.5/dist-packages (from matplotlib>=1.3.1->comparem)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from kiwisolver>=1.0.1->matplotlib>=1.3.1->comparem)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from cycler>=0.10->matplotlib>=1.3.1->comparem)

**Then i Run it**


(base) jmanuel@galileo:~$ python3 /usr/local/bin/comparem -h
Traceback (most recent call last):
  File "/usr/local/bin/comparem", line 37, in <module>
    from comparem.main import OptionsParser
  File "/usr/local/lib/python3.5/dist-packages/comparem/main.py", line 33, in <module>
    from comparem.plots.heatmap import Heatmap
  File "/usr/local/lib/python3.5/dist-packages/comparem/plots/heatmap.py", line 33, in <module>
    from biolib.plots.abstract_plot import AbstractPlot
  File "/usr/local/lib/python3.5/dist-packages/biolib/plots/abstract_plot.py", line 95
    self.logger.error(f'Unrecognized image format: {img_format}')
                                                               ^
SyntaxError: invalid syntax

**Comment by dparks1134** [comment]
Hi. Sorry for the slow reply. I've been on vacation. I'm not sure what to recommend as I can't reproduce this issue. Best I can suggest given the error message is to make sure you have the latest version of biolib which is 0.1.6.

**Comment by eik-dahms** [comment]
I had the same issue. When I switched from 3.5 to 3.8 this error was gone.
