### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by metacrobe** [dparks1134/CompareM#5]
Greetings--
First, I realize the project is in development so you may not want to hear any issues :)

I have tried numerous way of installing the latest version of CompareM (0.0.13) including pip install and building/installing from setup.py but continue to get errors when running commands. I was successful installing 0.0.5. 

Here are my platform details and two examples if errors. By the way, comparem -h works fine. 
Thanks a bunch

I am on a Ubuntu 14.04
Prodigal V2.6.2: February, 2015 (I have tried newer versions of prodigal)
diamond version 0.8.5
BLAST 2.4.0+
>>> print biolib.__version__ 
0.0.23

for example, when I run codon_usage:
temp_comparem$ comparem stop_usage 1.fna_files/ out_stuff
Traceback (most recent call last):
  File "/usr/local/bin/comparem", line 277, in <module>
    logger_setup(args.output_dir, "comparem.log", "CompareM", version(), args.silent)
AttributeError: 'Namespace' object has no attribute 'output_dir'

and the aai_wf...
j@j-h8-1090t:~/Documents/Analytics/Software_testing/temp_comparem$ comparem aai_wf test_contigs/ test_aai_wf
[2016-06-14 13:20:20] INFO: CompareM v0.0.13
[2016-06-14 13:20:20] INFO: comparem aai_wf test_contigs/ test_aai_wf
[2016-06-14 13:20:20] INFO: Identifying genes within genomes: 
  Finished processing 4 of 4 (100.00%) genomes.
[2016-06-14 13:20:25] INFO: Identified genes written to: test_aai_wf/genes
[2016-06-14 13:20:25] INFO: Appending genome identifiers to all gene identifiers.
[2016-06-14 13:20:25] INFO: Creating diamond database (be patient!).
[2016-06-14 13:20:26] INFO: Identifying hits between all pairs of genomes (be patient!).
[2016-06-14 13:20:34] INFO: Creating table with hits.
[2016-06-14 13:20:34] INFO: Sorting table with hits.
[2016-06-14 13:20:34] INFO: Reciprocal blast hits written to: test_aai_wf/rblast
[2016-06-14 13:20:34] INFO: Calculating length of genes.
[2016-06-14 13:20:34] INFO: Indexing blast hits.
[2016-06-14 13:20:34] INFO: Calculating amino acid identity between all 6 pairs of genomes:
  Finished processing 6 of 6 (100.00%) pairs.
[2016-06-14 13:20:34] INFO: Summarizing AAI results.

Unexpected error: <type 'exceptions.TypeError'>
Traceback (most recent call last):
  File "/usr/local/bin/comparem", line 293, in <module>
    parser.parse_options(args)
  File "/usr/local/lib/python2.7/dist-packages/comparem/main.py", line 494, in parse_options
    self.aai(options)
  File "/usr/local/lib/python2.7/dist-packages/comparem/main.py", line 210, in aai
    options.output_dir)
  File "comparem/aai_calculator.pyx", line 389, in comparem.aai_calculator.AAICalculator.run (./comparem/aai_calculator.c:5680)
TypeError: not enough arguments for format string
j@j-h8-1090t:~/Documents/Analytics/Software_testing/temp_comparem$

**Comment by dparks1134** [comment]
Thanks for the report. I am working on getting CompareM in a stable state and hope to have a version ready for public use in the next few weeks.

**Comment by dparks1134** [comment]
Resolved in v0.0.14.

**Comment by dparks1134** [comment]
Just an FYI, that CompareM v0.0.16 has been released. This _should_ be ready for public use. If you run into any problems, please let me know and I will work to resolve it ASAP.
