### ISSUE TITLE
Heatmap

### ISSUE THREAD

**Issue by jarrodscott** [dparks1134/CompareM#7]
Hello--Just wondering if the heatmap functionality should work? If not, no big deal just trying to troubleshoot this error. Thanks! and thanks for a great suite of tools. 

Jarrod

[2016-10-14 17:17:10] INFO: CompareM v0.0.15
[2016-10-14 17:17:10] INFO: comparem heatmap 2.genes_faa_zeta_only_aai_wf/aai/aai_summary.tsv test.svg
[2016-10-14 17:17:10] INFO: Making heatmap.

Unexpected error: <type 'exceptions.IndexError'>
Traceback (most recent call last):
  File "./bin/comparem", line 375, in <module>
    parser.parse_options(args)
  File "/home/j/Documents/Analytics/CompareM_versions/CompareM/comparem/main.py", line 498, in parse_options
    self.heatmap(options)
  File "/home/j/Documents/Analytics/CompareM_versions/CompareM/comparem/main.py", line 403, in heatmap
    heatmapper = Heatmap(options.aai_summary_file, options.output_file)
  File "/home/j/Documents/Analytics/CompareM_versions/CompareM/comparem/plots/heatmap.py", line 45, in **init**
    self._parse_data(infile)
  File "/home/j/Documents/Analytics/CompareM_versions/CompareM/comparem/plots/heatmap.py", line 90, in _parse_data
    self.perc_ids[genome_to_index[g1]][genome_to_index[g2]] = 100.0 - data[g2][g1][0]
IndexError: list assignment index out of range

**Comment by dparks1134** [comment]
Unfortunately, providing an informative heat map has proven difficult so this functionality has been removed. The latest version of CompareM does not provide this option on the CLI.
